services:
  db:
    image: postgres:17
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "kagari", "-d", "kagari" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: kagari
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: kagari
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    image: lzflywye/kagari:1.0.0-SNAPSHOT
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
